service: blog

plugins:
  - serverless-plugin-typescript

package:
  include:
    - src/**

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  apiGateway:
    # Delete this line after upgrading to v3.0.0 since it will be the default
    shouldStartNameWithService: true
  # Delete this line after upgrading to v3.0.0 since it will be the default
  lambdaHashingVersion: 20201221
  environment:
    ARTICLES_TABLE_NAME: !Ref ArticlesTable
    SERIES_TABLE_NAME: !Ref SeriesTable
    DEFAULT_BUCKET_NAME: !Ref DefaultBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AWS::StackName}-*
        - Effect: Allow
          Action:
            - s3:*
          Resource: !Sub arn:aws:s3:::${AWS::StackName}-*

functions:
  getArticle:
    handler: src/functions/get-article.handler
    events:
      - http:
          path: article/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  getSeries:
    handler: src/functions/get-series.handler
    events:
      - http:
          path: series/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    ArticlesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    SeriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    DefaultBucket:
      Type: AWS::S3::Bucket
      Properties:
        VersioningConfiguration:
          Status: Enabled
    PublicBucket:
      Type: AWS::S3::Bucket
      Properties:
        VersioningConfiguration:
          Status: Enabled
    PublicBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref PublicBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Principal: "*"
              Resource: !Sub ${PublicBucket.Arn}/*
